import Head from 'next/head';
import Image from 'next/image';
import { Button, Space, DatePicker, Card, PageHeader } from 'antd';
import Layout from '../components/Layout/Layout';
import axios from 'axios';
import TableComponent from '../components/Table/TableComponent';

export async function getServerSideProps() {
  try {
    const res = await fetch(`${process.env.API_HOST}/example`);
    const data = await res.json();
    if (!data) {
      return {
        notFound: true
      };
    }
    return { props: { data } };
  } catch (error) {
    return { props: null };
  }
}

export default function Home({ data }) {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">{data && <TableComponent data={data} />}</div>
    </Layout>
  );
}
